site_name: Zell 2036 (UNDER CONSTRUCTION)
repo_url: https://tangled.sh/@zell2036.com/zell2036

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.png
  icon:
    repo: fontawesome/brands/github
    annotation: material/star-four-points-circle
  features:
    - search.suggest
    - search.share
    - navigation.footer
    - navigation.path
#    - navigation.tabs
#    - navigation.tabs.sticky
    - navigation.top
    - navigation.indexes
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.tooltips
  palette:
    # Palette toggle for light mode
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    # Palette toggle for dark mode
    - scheme: default
      primary: red
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

extra:
  social:
    - icon: fontawesome/brands/bluesky
      link: https://bsky.app/profile/zell2036.com
    - icon: fontawesome/brands/github
      link: https://github.com/xaviervxz/
    - icon: fontawesome/solid/paper-plane
      link: mailto:inquiries@zell2036.com?subject=About%20the%20Website

plugins:
  - gen-files:
      scripts:
      - gen_doc_stubs.py
  - search
  - meta
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - git-revision-date-localized:
      enable_creation_date: true
      type: date
  - glightbox
  - ezlinks
#  - mkdocs-backlinks # Would be cool; not plug & play, though
  - macros:
      module_name: misc_macros

markdown_extensions:
  - abbr
  - attr_list
  - md_in_html
  - admonition
  - toc:
      permalink: true
      title: On This Page
      toc_depth: 4
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      pygments_lang_class: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.mark
  - pymdownx.caret
